apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc-1
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-s3-1
